### PR TITLE
Allow querying by custom External ID

### PR DESCRIPTION
**Pull request by olgakogan**
added get_by_custom_id to query by a custom field that was defined as an External ID

### CODE REVIEW

**Comment by olgakogan** [comment]
@nickcatal any chance you can take a look in the upcoming week, so I can use this in our code? Thanks!

**Comment by nickcatal** [comment]
Bah! I didn't notice this. Sorry.

@olgakogan  this looks good, can you update the README to include some details about this? Also if you could bump the version in setup.py up a tick that'd be great as well.

**Comment by olgakogan** [comment]
@nickcatal thanks! 
(just added the required changes)

**Comment by nickcatal** [comment]
@olgakogan Thanks!!!

@scottpersinger can you merge this in to `master` then create a `v0.67.2` release/tag. That should cause the CI system to deploy to pypi

**Pull request merged**
